---
- name: Install Apache2 web server
  hosts: all
  become: yes
  ignore_unreachable: yes
  tasks:
    - name: Update apt cache (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache2 (Debian)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache2 is running and enabled (Debian)
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"