---
- name: Validate and Install Required Application
  hosts: all
  gather_facts: no
  ignore_errors: no
  tasks:
    - name: Check if {{ required_app }} is installed
      command: "which {{ required_app }}"
      register: app_check

    - name: Display the result of the app check
      debug:
        msg: "The command 'which {{ required_app }}' returned: {{ app_check.stdout }}"
