---
- name: Check for pending updates on Ubuntu
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check for pending updates
      command: apt list --upgradable
      register: update_output
      changed_when: false

    - name: Show update information
      debug:
        msg: "Pending updates:\n{{ update_output.stdout_lines | join('\n') }}"
      when: update_output.stdout_lines | length > 0
