---
- name: Check if the required app is installed
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if {{ required_app }} is installed
      command: "which {{ required_app }}"
      register: app_check
      ignore_errors: yes