---
- name: Check for pending updates on Ubuntu
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check for pending updates
      command: apt list --upgradable
      register: update_output
      changed_when: false

    - name: Save update information to CSV
      copy:
        dest: /tmp/updates.csv
        content: |
          {% for line in update_output.stdout_lines %}
          {{ line }}
          {% endfor %}
      when: update_output.stdout_lines | length > 0
