---
- name: Validate and Install Required Application
  hosts: all
  gather_facts: no
  ignore_errors: no
  tasks:
    - name: Check if {{ required_app }} is installed
      command: "which {{ required_app }}"
      register: app_check
