---
- name: Ensure the required app is installed
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install {{ required_app }} if not present
      package:
        name: "{{ required_app }}"
        state: present
      when: app_check.rc != 0