---
- name: Ensure the required app is installed
  hosts: all
  gather_facts: no

  tasks:
    - name: Install {{ required_app }} if not present
      package:
        name: "{{ required_app }}"
        state: present
      when: app_check.rc != 0