---
- name: Ensure the required app is installed
  hosts: localhost
  gather_facts: yes
  vars:
    required_app: "curl"  # Change this to the app you want to install

  tasks:
    - name: Install {{ required_app }} if not present
      package:
        name: "{{ required_app }}"
        state: present
      when: app_check.rc != 0