---
- name: Install Jenkins on Ubuntu
  hosts: all
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - openjdk-11-jdk
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Add Jenkins repository key
      shell: curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      shell: echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Verify Jenkins is running
      command: systemctl status jenkins
      register: jenkins_status
      ignore_errors: yes

    - name: Display Jenkins service status
      debug:
        var: jenkins_status.stdout_lines