---
- name: Gather System Facts
  hosts: all
  gather_facts: yes

  tasks:
    - name: Save facts to variable
      set_fact:
        system_info:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }}"
          ip: "{{ ansible_default_ipv4.address }}"

- name: Send System Facts via Webhook
  hosts: localhost
  gather_facts: no

  vars:
    webhook_url: "https://prod-12.westus.logic.azure.com:443/workflows/b1f0d40b084d44ffa04b2747541d5c8e/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=VDoLSyVfRHScodWiyl5WvrcZiWI6hjWoDpHAGyzpAkA"

  tasks:
    - name: Send collected facts to webhook
      uri:
        url: "{{ webhook_url }}"
        method: POST
        body: "{{ system_info | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"