---
- name: Save data into CSV
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Define data to save
      set_fact:
        csv_data:
          - ["Name", "Age", "City"]
          - ["Alice", "30", "New York"]
          - ["Bob", "25", "Los Angeles"]
          - ["Charlie", "35", "Chicago"]

    - name: Write data to CSV file
      copy:
        dest: /tmp/output.csv
        content: |
          {% for row in csv_data %}
          {{ row | join(',') }}
          {% endfor %}