---
- name: Patch and update Ubuntu machine
  hosts: all
  become: yes  # Run as a privileged user (root)
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Clean up unnecessary packages
      apt:
        autoremove: yes
        autoclean: yes
