---
- name: Patch and update Ubuntu machine
  hosts: all
  become: yes
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
